### ISSUE TITLE
I can not make browser pubsub example working - Uncaught (in promise) Error: PublishError.InsufficientPeers

### ISSUE THREAD

**Issue by scenaristeur** [libp2p/js-libp2p-examples#70] opened 2023-11-03 09:28 UTC
I'm on Linux Mint 21.2 Cinnamon 5.15.0-87-generic #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 GNU/Linux
node V18.18.0

js-libp2p-examples@1.0.0 /home/smag/dev/js-libp2p-examples
└─┬ @libp2p/example-browser-pubsub@1.0.0 -> ./examples/js-libp2p-example-browser-pubsub
  ├── @chainsafe/libp2p-gossipsub@10.1.0
  ├── @chainsafe/libp2p-noise@13.0.2
  ├── @chainsafe/libp2p-yamux@5.0.0
  ├── @libp2p/webrtc@3.2.5
  ├── @libp2p/websockets@7.0.10
  ├── @multiformats/multiaddr@12.1.8
  ├── libp2p@0.46.16
  ├── test-ipfs-example@1.1.0
  └── vite@4.5.0

![image](https://github.com/libp2p/js-libp2p-examples/assets/4020744/b29795c2-737d-4ce8-9e15-a14b9725cd73)

**Comment by silkroadnomad** [comment] 2023-11-06 15:21
I can confirm. Your screenshot says, you do not have any "topic peers". In my case its the exact same problem. I am subscribing to the topic, but I don't get any topic peers. If I hit the "subscribe to topic" button about 5-10 times fast after another, I suddenly receive a sdp (WebRTC) error message:
```
initiate-connection.ts:75 Uncaught (in promise) CodeError: SDP handshake aborted
    at AbortSignal.sdpAbortedListener (initiate-connection.ts:75:31)
    at AbortSignal.onAbort (index.ts:14:16)
    at AbortSignal.onAbort (index.ts:14:16)

and 

dial-queue.ts:253 Uncaught (in promise) CodeError: The task was aborted.
    at dial-queue.ts:253:25
    at async DefaultConnectionManager.openConnection (index.ts:517:24)
    at async HTMLButtonElement.dialMultiaddrButton (+page.svelte:127:36)
````
SDP means probably that both peers (both browsers) cannot connect via WebRTC to each other. 
The example uses WebRTC in the "listen" section of the libp2p config. Not sure if we need WebRTC inside the transport section too! (I can give it a try but I am still a bit new here) 

I was using Opera and Firefox for that test. Brave gives the same error message after first subscribing.

**Comment by silkroadnomad** [comment] 2023-11-06 15:58
might be related mentioned fixes https://github.com/libp2p/js-libp2p/discussions/2179
(e.g. upgraded to libp2p@0.46.18) didn't seem to help.

**Comment by sOniri** [comment] 2023-12-06 09:03
I tried without using webrtc and only the websocket address and I get the same error "insufficient peers" . It seems that when using circuit-relay with websocket produces this error . when using webrtc in chrome it works . The same applies when running in node and not the browser .

**Comment by 3mg** [comment] 2024-01-04 14:48
I faced the same error.

**Comment by achingbrain** [comment] 2024-09-23 06:52
> Uncaught (in promise) Error: PublishError.InsufficientPeers

When you see this error, it's because the current node has published a message on a topic that has no subscribed peers.  

The error is thrown because the message has not left the current node, so it will never be received by any other network peers.

In a [@chainsafe/libp2p-gossipsub@13.x.x](https://github.com/ChainSafe/js-libp2p-gossipsub/releases/tag/v13.0.0) this was changed to `PublishError.NoPeersSubscribedToTopic` which is hopefully more descriptive.

There's also a `allowPublishToZeroTopicPeers` config option you can pass to GossipSub to suppress this error but it's not advised since you'll not know if your message will reach the network or not.

> CodeError: SDP handshake aborted
> CodeError: The task was aborted.

This means the task was cancelled before it competed, usually because the remote failed to send data within the timeout.

> webRTC: ICE failed, add a STUN server and see about:webrtc for more details 

This normally means the browser [RTCPeerConnection](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection) couldn't determine it's external ip/port combination and you should add [STUN servers](https://gist.github.com/mondain/b0ec1cf5f60ae726202e) to the `@libp2p/webrtc` transport config.

Recent `@libp2p/webrtc` releases have a default set of STUN servers already so this should become less of an issue.

> If you run the test inside the example directory like `npm run test:firefox` this test also crashes

I can't replicate this, everything works in the latest versions.

> Firefox does not normally support webrtc on the localhost domain

There are [bugs in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1659672) around using WebRTC in an offline/non-routable environment, it may have something to do with it.

If you are still having problems with WebRTC connections, [this is a useful guide](https://docs.libp2p.io/guides/getting-started/webrtc/).

I'm going to close this issue since the original issue is caused by not having subscribed peers, and since [CI is passing for the browser pubsub example](https://github.com/libp2p/js-libp2p-examples/actions/runs/10969971691/job/30463307872) - please re-open if you are still having problems.

**Closed by achingbrain** 2024-09-23 06:52 UTC
